import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { publicEnv } from '@/lib/env';
import AuthGuard from '@/components/AuthGuard';

void publicEnv;

export const metadata: Metadata = {
  title: "MCP Server Manager",
  description: "Generated by MCP Server Manager",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>
          <AuthGuard>
            {children}
          </AuthGuard>
        </Providers>
      </body>
    </html>
  );
}
